import { normalizePath } from 'obsidian';
import { IParaCoreApi } from './types';

export function registerFinanceTemplateContributions(
	api: IParaCoreApi,
	transactionsPath: string,
): void {
	const transactionsFolder = normalizePath(transactionsPath);
	const reportsFolder = normalizePath(transactionsPath.replace(/\/Transactions$/i, '/Reports'));
	const projectSummaryBlock = [
		'### Project Summary',
		'```dataviewjs',
		`const records = dv.pages('"${transactionsFolder}"').where((page) => page.project && String(page.project) === String(dv.current().file.link));`,
		'const expenses = records.where((page) => page.type === "finance-expense");',
		'const incomes = records.where((page) => page.type === "finance-income");',
		'const expenseTotal = expenses.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
		'const incomeTotal = incomes.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
		'const balance = incomeTotal - expenseTotal;',
		'const current = dv.current();',
		'const hasFinanceBudget = Object.prototype.hasOwnProperty.call(current, "finance_budget");',
		'const rawBudget = hasFinanceBudget ? current.finance_budget : current.budget;',
		'const budget = rawBudget === null || rawBudget === undefined || rawBudget === "" ? NaN : Number(rawBudget);',
		'const rows = [',
		'  ["Expenses", expenseTotal.toFixed(2)],',
		'  ["Income", incomeTotal.toFixed(2)],',
		'  ["Balance", balance.toFixed(2)],',
		'  ["Transactions", String(records.length)],',
		'];',
		'if (!Number.isNaN(budget)) {',
		'  const spent = expenseTotal;',
		'  const remaining = budget - spent;',
		'  const usage = budget === 0 ? 0 : (spent / budget) * 100;',
		'  rows.push(["Budget", budget.toFixed(2)]);',
		'  rows.push(["Remaining", remaining.toFixed(2)]);',
		'  rows.push(["Budget used", `${usage.toFixed(1)}%`]);',
		'}',
		'dv.table(["Metric", "Value"], rows);',
		'```',
	].join('\n');

	const areaSummaryBlock = [
		'### Area Summary',
		'```dataviewjs',
		`const records = dv.pages('"${transactionsFolder}"').where((page) => page.area && String(page.area) === String(dv.current().file.link));`,
		'const expenses = records.where((page) => page.type === "finance-expense");',
		'const incomes = records.where((page) => page.type === "finance-income");',
		'const expenseTotal = expenses.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
		'const incomeTotal = incomes.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
		'const projectCount = new Set(records.array().map((page) => page.project).filter(Boolean).map((value) => String(value))).size;',
		'dv.table(["Metric", "Value"], [',
		'  ["Expenses", expenseTotal.toFixed(2)],',
		'  ["Income", incomeTotal.toFixed(2)],',
		'  ["Balance", (incomeTotal - expenseTotal).toFixed(2)],',
		'  ["Transactions", String(records.length)],',
		'  ["Linked projects", String(projectCount)],',
		']);',
		'```',
	].join('\n');

	api.registerTemplateContribution({
		id: 'finance.project-expenses',
		domainId: 'finance',
		target: 'project',
		slot: 'project.domainViews',
		order: 100,
		render: () => [
			'## Finance',
			'',
			'> Add `finance_budget` to project frontmatter if you want budget tracking here.',
			'',
			projectSummaryBlock,
			'',
			'### Project Expenses',
			'```dataview',
			'TABLE dateTime, amount, currency, category, source',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-expense" AND project = this.file.link',
			'SORT dateTime DESC',
			'```',
			'',
			'### Project Income',
			'```dataview',
			'TABLE dateTime, amount, currency, category, source',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-income" AND project = this.file.link',
			'SORT dateTime DESC',
			'```',
		].join('\n'),
	});

	api.registerTemplateContribution({
		id: 'finance.area-overview',
		domainId: 'finance',
		target: 'area',
		slot: 'area.domainViews',
		order: 100,
		render: () => [
			'## Financial Overview',
			'',
			areaSummaryBlock,
			'',
			'### Area Expenses',
			'```dataview',
			'TABLE dateTime, amount, currency, category, project',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-expense" AND area = this.file.link',
			'SORT dateTime DESC',
			'```',
			'',
			'### Area Income',
			'```dataview',
			'TABLE dateTime, amount, currency, category, project',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-income" AND area = this.file.link',
			'SORT dateTime DESC',
			'```',
		].join('\n'),
	});

	api.registerTemplateContribution({
		id: 'finance.dashboard-current-month-expenses',
		domainId: 'finance',
		target: 'dashboard',
		slot: 'dashboard.domainViews',
		order: 100,
		render: () => [
			'## Finance This Month',
			'',
			'```dataviewjs',
			`const records = dv.pages('"${transactionsFolder}"').where((page) => (page.type === "finance-expense" || page.type === "expense") && page.dateTime);`,
			'const readIsoDate = (value) => {',
			'  if (!value) return null;',
			'  if (typeof value === "string") return value.slice(0, 10);',
			'  if (typeof value.toISO === "function") return value.toISO().slice(0, 10);',
			'  if (typeof value.toISODate === "function") return value.toISODate();',
			'  return String(value).slice(0, 10);',
			'};',
			'const currentMonthKey = window.moment().format("YYYY-MM");',
			'const currentMonthExpenses = records.where((page) => {',
			'  const isoDate = readIsoDate(page.dateTime);',
			'  return isoDate && isoDate.slice(0, 7) === currentMonthKey;',
			'});',
			'const categories = new Map();',
			'for (const page of currentMonthExpenses.array()) {',
			'  const key = String(page.category ?? "uncategorized");',
			'  categories.set(key, (categories.get(key) ?? 0) + Number(page.amount ?? 0));',
			'}',
			'const entries = Array.from(categories.entries()).sort((a, b) => b[1] - a[1]).slice(0, 8);',
			'dv.table(["Category", "Amount"], entries.map(([label, amount]) => [label, `${Number(amount).toFixed(2)} RUB`]));',
			'if (entries.length === 0) {',
			'  dv.paragraph("_No expenses in this month._");',
			'} else {',
			'  const colors = ["#d97706", "#0891b2", "#7c3aed", "#dc2626", "#16a34a", "#2563eb", "#9333ea", "#ea580c"];',
			'  const radius = 70;',
			'  const circumference = 2 * Math.PI * radius;',
			'  const total = entries.reduce((sum, [, amount]) => sum + amount, 0);',
			'  let offset = 0;',
			'  const segments = entries.map(([label, amount], index) => {',
			'    const fraction = total === 0 ? 0 : amount / total;',
			'    const dash = fraction * circumference;',
			'    const color = colors[index % colors.length];',
			'    const segment = `<circle r="${radius}" cx="90" cy="90" fill="transparent" stroke="${color}" stroke-width="36" stroke-dasharray="${dash} ${circumference - dash}" stroke-dashoffset="${-offset}" transform="rotate(-90 90 90)"></circle>`;',
			'    offset += dash;',
			'    return segment;',
			'  }).join("");',
			'  const legend = entries.map(([label, amount], index) => {',
			'    const color = colors[index % colors.length];',
			'    const percentage = total === 0 ? 0 : (amount / total) * 100;',
			'    return `<div style="display:flex; align-items:center; gap:8px; margin:4px 0;"><span style="display:inline-block; width:12px; height:12px; border-radius:999px; background:${color};"></span><span>${label}: ${amount.toFixed(2)} RUB (${percentage.toFixed(1)}%)</span></div>`;',
			'  }).join("");',
			'  const wrapper = dv.el("div", "");',
			'  wrapper.innerHTML = `<div style="display:grid; grid-template-columns:minmax(180px, 220px) 1fr; gap:16px; align-items:center; margin-top: 12px;"><svg viewBox="0 0 180 180" width="180" height="180">${segments}<circle r="40" cx="90" cy="90" fill="var(--background-primary)"></circle><text x="90" y="86" text-anchor="middle" font-size="12" fill="var(--text-muted)">Month</text><text x="90" y="104" text-anchor="middle" font-size="14" fill="var(--text-normal)">${total.toFixed(0)}</text></svg><div>${legend}</div></div>`;',
			'}',
			'```',
			'',
			'## Finance This Year',
			'',
			'```dataviewjs',
			`const transactionRecords = dv.pages('"${transactionsFolder}"').where((page) => page.dateTime && (page.type === "finance-expense" || page.type === "finance-income" || page.type === "expense" || page.type === "income"));`,
			'const readIsoDate = (value) => {',
			'  if (!value) return null;',
			'  if (typeof value === "string") return value.slice(0, 10);',
			'  if (typeof value.toISO === "function") return value.toISO().slice(0, 10);',
			'  if (typeof value.toISODate === "function") return value.toISODate();',
			'  return String(value).slice(0, 10);',
			'};',
			'const currentYear = window.moment().format("YYYY");',
			'const labels = Array.from({ length: 12 }, (_, index) => window.moment(`${currentYear}-01-01`).add(index, "months").format("MMM"));',
			'const expenses = labels.map(() => 0);',
			'const incomes = labels.map(() => 0);',
			'for (const page of transactionRecords.array()) {',
			'  const isoDate = readIsoDate(page.dateTime);',
			'  if (!isoDate || !isoDate.startsWith(`${currentYear}-`)) {',
			'    continue;',
			'  }',
			'  const monthIndex = Number(isoDate.slice(5, 7)) - 1;',
			'  if (!Number.isFinite(monthIndex) || monthIndex < 0 || monthIndex > 11) {',
			'    continue;',
			'  }',
			'  if (String(page.type) === "finance-income" || String(page.type) === "income") {',
			'    incomes[monthIndex] += Number(page.amount ?? 0);',
			'  } else {',
			'    expenses[monthIndex] += Number(page.amount ?? 0);',
			'  }',
			'}',
			'dv.table(["Month", "Expenses", "Income"], labels.map((label, index) => [label, `${expenses[index].toFixed(2)} RUB`, `${incomes[index].toFixed(2)} RUB`]));',
			'const maxValue = Math.max(1, ...expenses, ...incomes);',
			'const chartHeight = 220;',
			'const chartWidth = 700;',
			'const padding = 30;',
			'const columnGroupWidth = (chartWidth - padding * 2) / labels.length;',
			'const columnWidth = Math.max(10, Math.floor(columnGroupWidth / 3));',
			'const scale = (value) => (value / maxValue) * (chartHeight - padding * 2);',
			'const bars = labels.map((label, index) => {',
			'  const expenseHeight = scale(expenses[index]);',
			'  const incomeHeight = scale(incomes[index]);',
			'  const x = padding + index * columnGroupWidth;',
			'  const expenseX = x + 4;',
			'  const incomeX = x + 4 + columnWidth + 6;',
			'  const baseY = chartHeight - padding;',
			'  return `',
			'    <rect x="${expenseX}" y="${baseY - expenseHeight}" width="${columnWidth}" height="${expenseHeight}" fill="#dc2626"></rect>',
			'    <rect x="${incomeX}" y="${baseY - incomeHeight}" width="${columnWidth}" height="${incomeHeight}" fill="#16a34a"></rect>',
			'    <text x="${x + columnGroupWidth / 2}" y="${chartHeight - 8}" text-anchor="middle" font-size="11" fill="var(--text-muted)">${label}</text>`;',
			'}).join("");',
			'const wrapper = dv.el("div", "");',
			'wrapper.innerHTML = `<div style="margin-top: 12px;"><svg viewBox="0 0 ${chartWidth} ${chartHeight}" width="100%" height="${chartHeight}"><line x1="${padding}" y1="${chartHeight - padding}" x2="${chartWidth - padding}" y2="${chartHeight - padding}" stroke="var(--text-muted)" stroke-width="1"></line>${bars}</svg><div style="display:flex; gap:16px; margin-top:8px;"><span><span style="display:inline-block; width:12px; height:12px; background:#dc2626; margin-right:6px;"></span>Expenses</span><span><span style="display:inline-block; width:12px; height:12px; background:#16a34a; margin-right:6px;"></span>Income</span></div></div>`;',
			'```',
			'',
			'## Finance reports',
			'```dataview',
			'TABLE periodLabel, periodKind, openingBalance, totalExpenses, totalIncome, closingBalance, budget',
			`FROM "${reportsFolder}"`,
			'WHERE type = "finance-report"',
			'SORT periodStart DESC',
			'```',
		].join('\n'),
	});
}
