import { normalizePath } from 'obsidian';
import { IParaCoreApi } from './types';

export function registerFinanceTemplateContributions(
	api: IParaCoreApi,
	transactionsPath: string,
): void {
	const transactionsFolder = normalizePath(transactionsPath);
	const projectSummaryBlock = [
		'### Project Summary',
		'```dataviewjs',
		`const records = dv.pages('"${transactionsFolder}"').where((page) => page.project && String(page.project) === String(dv.current().file.link));`,
		'const expenses = records.where((page) => page.type === "finance-expense");',
		'const incomes = records.where((page) => page.type === "finance-income");',
		'const expenseTotal = expenses.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
		'const incomeTotal = incomes.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
		'const balance = incomeTotal - expenseTotal;',
		'const current = dv.current();',
		'const hasFinanceBudget = Object.prototype.hasOwnProperty.call(current, "finance_budget");',
		'const rawBudget = hasFinanceBudget ? current.finance_budget : current.budget;',
		'const budget = rawBudget === null || rawBudget === undefined || rawBudget === "" ? NaN : Number(rawBudget);',
		'const rows = [',
		'  ["Expenses", expenseTotal.toFixed(2)],',
		'  ["Income", incomeTotal.toFixed(2)],',
		'  ["Balance", balance.toFixed(2)],',
		'  ["Transactions", String(records.length)],',
		'];',
		'if (!Number.isNaN(budget)) {',
		'  const spent = expenseTotal;',
		'  const remaining = budget - spent;',
		'  const usage = budget === 0 ? 0 : (spent / budget) * 100;',
		'  rows.push(["Budget", budget.toFixed(2)]);',
		'  rows.push(["Remaining", remaining.toFixed(2)]);',
		'  rows.push(["Budget used", `${usage.toFixed(1)}%`]);',
		'}',
		'dv.table(["Metric", "Value"], rows);',
		'```',
	].join('\n');

	const areaSummaryBlock = [
		'### Area Summary',
		'```dataviewjs',
		`const records = dv.pages('"${transactionsFolder}"').where((page) => page.area && String(page.area) === String(dv.current().file.link));`,
		'const expenses = records.where((page) => page.type === "finance-expense");',
		'const incomes = records.where((page) => page.type === "finance-income");',
		'const expenseTotal = expenses.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
		'const incomeTotal = incomes.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
		'const projectCount = new Set(records.array().map((page) => page.project).filter(Boolean).map((value) => String(value))).size;',
		'dv.table(["Metric", "Value"], [',
		'  ["Expenses", expenseTotal.toFixed(2)],',
		'  ["Income", incomeTotal.toFixed(2)],',
		'  ["Balance", (incomeTotal - expenseTotal).toFixed(2)],',
		'  ["Transactions", String(records.length)],',
		'  ["Linked projects", String(projectCount)],',
		']);',
		'```',
	].join('\n');

	api.registerTemplateContribution({
		id: 'finance.project-expenses',
		domainId: 'finance',
		target: 'project',
		slot: 'project.domainViews',
		order: 100,
		render: () => [
			'## Finance',
			'',
			'> Add `finance_budget` to project frontmatter if you want budget tracking here.',
			'',
			projectSummaryBlock,
			'',
			'### Project Expenses',
			'```dataview',
			'TABLE dateTime, amount, currency, category, source',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-expense" AND project = this.file.link',
			'SORT dateTime DESC',
			'```',
			'',
			'### Project Income',
			'```dataview',
			'TABLE dateTime, amount, currency, category, source',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-income" AND project = this.file.link',
			'SORT dateTime DESC',
			'```',
		].join('\n'),
	});

	api.registerTemplateContribution({
		id: 'finance.area-overview',
		domainId: 'finance',
		target: 'area',
		slot: 'area.domainViews',
		order: 100,
		render: () => [
			'## Financial Overview',
			'',
			areaSummaryBlock,
			'',
			'### Area Expenses',
			'```dataview',
			'TABLE dateTime, amount, currency, category, project',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-expense" AND area = this.file.link',
			'SORT dateTime DESC',
			'```',
			'',
			'### Area Income',
			'```dataview',
			'TABLE dateTime, amount, currency, category, project',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-income" AND area = this.file.link',
			'SORT dateTime DESC',
			'```',
		].join('\n'),
	});

	api.registerTemplateContribution({
		id: 'finance.dashboard-current-month-expenses',
		domainId: 'finance',
		target: 'dashboard',
		slot: 'dashboard.domainViews',
		order: 100,
		render: () => [
			'## Finance This Month',
			'',
			'```dataviewjs',
			`const records = dv.pages('"${transactionsFolder}"').where((page) => page.type === "finance-expense" && page.dateTime);`,
			'const monthStart = window.moment().startOf("month");',
			'const monthEnd = window.moment().endOf("month");',
			'const currentMonthExpenses = records.where((page) => {',
			'  const value = window.moment(page.dateTime);',
			'  return value.isValid() && value.isBetween(monthStart, monthEnd, undefined, "[]");',
			'});',
			'const total = currentMonthExpenses.array().reduce((sum, page) => sum + Number(page.amount ?? 0), 0);',
			'dv.table(["Metric", "Value"], [',
			'  ["Current month expenses", total.toFixed(2)],',
			'  ["Transactions", String(currentMonthExpenses.length)],',
			']);',
			'```',
			'',
			'### Recent Expenses This Month',
			'```dataview',
			'TABLE dateTime, amount, currency, category, project, area',
			`FROM "${transactionsFolder}"`,
			'WHERE type = "finance-expense"',
			'  AND dateTime >= dateformat(date(today).monthStart, "yyyy-MM-dd")',
			'SORT dateTime DESC',
			'LIMIT 10',
			'```',
		].join('\n'),
	});
}
