export function buildFinanceReviewQueueNoteContent(transactionsFolder: string): string {
	return [
		'# Finance Review Queue',
		'',
		'> Review finance candidates that are waiting for confirmation, still need manual attention, or were marked as duplicates.',
		'',
		'## Queue Summary',
		'',
		'```dataviewjs',
		`const records = dv.pages('"${transactionsFolder}"').where((page) => ["pending-approval", "needs-attention", "duplicate"].includes(String(page.status ?? "")));`,
		'const pending = records.where((page) => String(page.status ?? "") === "pending-approval");',
		'const attention = records.where((page) => String(page.status ?? "") === "needs-attention");',
		'const duplicates = records.where((page) => String(page.status ?? "") === "duplicate");',
		'dv.table(["Queue", "Count"], [',
		'  ["Pending approval", String(pending.length)],',
		'  ["Needs attention", String(attention.length)],',
		'  ["Duplicates", String(duplicates.length)],',
		'  ["Total", String(records.length)],',
		']);',
		'```',
		'',
		'## Pending Approval',
		'',
		'```dataview',
		'TABLE file.link AS Record, dateTime, amount, currency, description, category, source, artifact',
		`FROM "${transactionsFolder}"`,
		'WHERE status = "pending-approval"',
		'SORT dateTime DESC',
		'```',
		'',
		'## Needs Attention',
		'',
		'```dataview',
		'TABLE file.link AS Record, dateTime, description, source, artifact',
		`FROM "${transactionsFolder}"`,
		'WHERE status = "needs-attention"',
		'SORT dateTime DESC',
		'```',
		'',
		'## Duplicates',
		'',
		'> Use the command **Open duplicate merge queue** from the command palette to resolve duplicate candidates.',
		'',
		'```dataview',
		'TABLE file.link AS Duplicate, duplicate_of AS Original, dateTime, amount, currency, description, source',
		`FROM "${transactionsFolder}"`,
		'WHERE status = "duplicate"',
		'SORT dateTime DESC',
		'```',
		'',
	].join('\n');
}
